// Copyright 2014 The Azul3D Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#define DFLT_XKB_CONFIG_ROOT "/usr/share/X11/xkb"
#define DEFAULT_XKB_MODEL "pc105"
#define DEFAULT_XKB_RULES "evdev"
#define DEFAULT_XKB_LAYOUT "us"

#include "libxkbcommon/src/xkbcomp/action.c"
#include "libxkbcommon/src/xkbcomp/action.h"
#include "libxkbcommon/src/xkbcomp/ast.h"
#include "libxkbcommon/src/xkbcomp/ast-build.c"
#include "libxkbcommon/src/xkbcomp/ast-build.h"
#include "libxkbcommon/src/xkbcomp/expr.c"
#include "libxkbcommon/src/xkbcomp/expr.h"
#include "libxkbcommon/src/xkbcomp/include.c"
#include "libxkbcommon/src/xkbcomp/include.h"
#include "libxkbcommon/src/xkbcomp/symbols.c"
#include "libxkbcommon/src/xkbcomp/compat.c"
#include "libxkbcommon/src/xkbcomp/keycodes.c"
#include "libxkbcommon/src/xkbcomp/keymap.c"
#include "libxkbcommon/src/xkbcomp/keymap-dump.c"
#include "libxkbcommon/src/xkbcomp/keywords.c"
#include "libxkbcommon/src/xkbcomp/parser-priv.h"
#include "libxkbcommon/src/xkbcomp/parser.c"
#include "libxkbcommon/src/xkbcomp/rules.c"
#include "libxkbcommon/src/xkbcomp/rules.h"
#include "libxkbcommon/src/xkbcomp/scanner.c"
#include "libxkbcommon/src/xkbcomp/types.c"
#include "libxkbcommon/src/xkbcomp/vmod.c"
#include "libxkbcommon/src/xkbcomp/vmod.h"
#include "libxkbcommon/src/xkbcomp/xkbcomp.c"
#include "libxkbcommon/src/xkbcomp/xkbcomp-priv.h"

#include "libxkbcommon/src/atom.c"
#include "libxkbcommon/src/atom.h"
#include "libxkbcommon/src/context.c"
#include "libxkbcommon/src/context.h"
#include "libxkbcommon/src/context-priv.c"
#include "libxkbcommon/src/compat.c"
#include "libxkbcommon/src/darray.h"
#include "libxkbcommon/src/keysym.c"
#include "libxkbcommon/src/keysym.h"
#include "libxkbcommon/src/keysym-utf.c"
//#include "libxkbcommon/src/ks_tables.h"
#include "libxkbcommon/src/keymap.c"
#include "libxkbcommon/src/keymap.h"
#include "libxkbcommon/src/keymap-priv.c"
#include "libxkbcommon/src/scanner-utils.h"
#include "libxkbcommon/src/state.c"
#include "libxkbcommon/src/text.c"
#include "libxkbcommon/src/text.h"
#include "libxkbcommon/src/utf8.c"
#include "libxkbcommon/src/utf8.h"
#include "libxkbcommon/src/utils.c"
#include "libxkbcommon/src/utils.h"


#include "libxkbcommon/src/x11/keymap.c"
#include "libxkbcommon/src/x11/state.c"
#include "libxkbcommon/src/x11/util.c"
#include "libxkbcommon/src/x11/x11-priv.h"
#include "libxkbcommon/src/context.h"
#include "libxkbcommon/src/keymap.h"
#include "libxkbcommon/src/atom.h"
